FROM ubuntu:latest

ENV FASTQ_RS_VERSION="v0.0.2"

RUN apt-get update && apt-get install -y wget \
	&& wget https://github.com/OscarAspelin95/fastq_rs/releases/download/${FASTQ_RS_VERSION}/fastq_rs-${FASTQ_RS_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
	&& tar -xf fastq_rs-${FASTQ_RS_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
    && chmod +x ./fastq_rs \
	&& mv ./fastq_rs /usr/local/bin


